### PR TITLE
simple select now accepts 0 as a value

### PR DESCRIPTION
**Pull request by Nyalab**
Hi,

We use your library at Overblog and we had issues with months in select fields. After investigating, i see that your code does not accept 0 as a value.

This PR fixes it.

Thanks for your time.

### CODE REVIEW

**Comment by furqanZafar** [comment]
Thanks! 👍  (javascript [sigh]) i think a better way to write that code would be to explicitly check using `typeof`
```
typeof value == \undefined
```

**Comment by Nyalab** [comment]
i don't know LS at all, and i did not want to break everything, that's why i only checked for a 0 value, but i think you can check to see if it is undefined yes 👍

**Comment by Nyalab** [comment]
can you just do a patch or minor release so we can update our app and make it work for us?

**Comment by furqanZafar** [comment]
done use release 2.0.2, sorry for the long delay (swamped at work)

**Comment by homam** [comment]
Let's use LiveScript `typeof!` operator:

```livescript
values = if !(typeof! a in <[Null Undefined]>) then [value] else []
```

**Pull request merged**
